# OpenTelemetry Collector Configuration
# Unified observability for Brivas Platform

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: 'brivas-services'
          scrape_interval: 15s
          static_configs:
            - targets:
              - 'api-gateway:8080'
              - 'voice-switch:8095'
              - 'temporal-worker:8096'
              - 'smsc:8081'
              - 'ussd-gateway:8080'
              - 'unified-messaging:8093'
              - 'billing:8084'

  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      disk:
      network:

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200

  attributes:
    actions:
      - key: environment
        value: production
        action: upsert
      - key: service.namespace
        value: brivas
        action: upsert

  resource:
    attributes:
      - key: deployment.environment
        value: ${DEPLOYMENT_ENV:-production}
        action: upsert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: brivas
    resource_to_telemetry_conversion:
      enabled: true

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: brivas_traces
    traces_table_name: traces
    logs_table_name: logs
    metrics_table_name: metrics
    ttl_days: 30
    timeout: 10s

  logging:
    loglevel: info

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

  pprof:
    endpoint: 0.0.0.0:1777

  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes]
      exporters: [otlp/jaeger, clickhouse]

    metrics:
      receivers: [otlp, prometheus, hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [prometheus, clickhouse]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse, logging]
