linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gosec
    - misspell
    - gocritic
    - revive
    - prealloc
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - goprintffuncname
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  gocyclo:
    min-complexity: 15
  
  gocognit:
    min-complexity: 20
  
  funlen:
    lines: 100
    statements: 50
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  dupl:
    threshold: 100
  
  nestif:
    min-complexity: 4
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
  
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - funlen
        - gocognit
        - gocyclo
    
    - path: mock_
      linters:
        - dupl
    
    - linters:
        - gocritic
      text: "hugeParam"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - third_party
    - testdata
  
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  unique-by-line: true

severity:
  default-severity: warning
  case-sensitive: false
  rules:
    - linters:
        - gosec
      severity: error
    - linters:
        - govet
      severity: error
